### ISSUE TITLE
Rename TMC in registration list

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/member-ui#71]
From Robin:
>One of the TMCs is having a cow because we have them listed as TMC UCONN, not TMC UCONN/SCRIPPS.

Will also need to update any existing records with the old name.

**Comment by shirey** [comment]
@yuanzhou Do not include a slash in the name of the TMC, this will definitely cause problems elsewhere.  Please ask Robin for the best name to use that doesn't include any reserved characters like this.
