### ISSUE TITLE
Upgrade uwsgi config and dependencies to work with Python 3.9

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/member-ui#83]
Test on the new DEV VM, link to issue https://github.com/hubmapconsortium/devops/issues/42

**Comment by humadragonbane** [comment]
uwsgi is now working on newly built dev and prod vm's 

some changes were made to the requirements for rhel 9


## Python venv install

## Pip Installations

asn1crypto==0.24.0
blinker==1.4
certifi==2019.6.16
#cffi==1.12.3 - this version is no longer working
cffi
chardet==3.0.4
click==7.0
cryptography==3.3.2
flask-mail==0.9.1
flask-marshmallow==0.10.1
flask-sqlalchemy==2.4.0
flask==1.1.1
globus-sdk==1.8.0
idna==2.8
itsdangerous==1.1.0
jinja2==2.11.3
markupsafe==1.1.1
marshmallow-sqlalchemy==0.17.0
marshmallow==2.19.5
phpserialize==1.3
pillow==8.4.0
pycparser==2.19
pyjwt[crypto]==1.7.1
pymysql==0.9.3
python-slugify==3.0.3
requests==2.25.1
six==1.12.0
sqlalchemy==1.3.6
text-unidecode==1.2
#urllib3==1.26.5 ---- no longer working
urllib3
werkzeug==0.15.5
