### ISSUE TITLE
Troubleshooting HM registration issue

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/member-ui#86]
Chris Csonka reported to our Chris Burke:

>Help! I was attempting to approve a new HuBMAP registration for Yuling Ma (yma8@bidmc.harvard.edu) yesterday afternoon. This person showed multiple (4?) "possible matching" profiles, but obviously NONE of them were an actual match. I clicked Approve and an error message displayed. Now this person is listed in both the Registrations AND Members, but if you try to click either a server error displays! Help!?

**Comment by humadragonbane** [comment]
There is an error message in the uwsgi-member-ui.log that corresponds with it. if it would be helpful to you.

```
member-ui/logs/uwsgi-member-ui.log:[pid: 132950|app: 0|req: 2179/4672] 130.49.164.16 () {60 vars in 1828 bytes} [Fri Oct  6 16:29:41 2023] GET /registrations/2adda287-a750-44d2-abbd-026469a1763e => generated 290 bytes in 4062 msecs (HTTP/2.0 500) 3 headers in 98 bytes
 (1 switches on core 0) 
```
                                                                                                                                                                                                                                                
[12:55](https://hubmapconsortium.slack.com/archives/D05C6LP1SBX/p1696611359410759)

```
member-ui/logs/uwsgi-member-ui.log:user_is_admin(): No user found with globus_user_id: 2adda287-a750-44d2-abbd-026469a1763e                                                                                                                                                 
member-ui/logs/uwsgi-member-ui.log:user_is_approved(): No user found with globus_user_id: 2adda287-a750-44d2-abbd-026469a1763e****
```

**Comment by yuanzhou** [comment]
I disabled the matching profile to prevent such issue from happening in the future. Chris Csonka was able to view the profile page. But failed to approved due to a another error:

```
[Errno 2] No such file or directory: '/backup/profile-pics/2adda287-a750-44d2-abbd-026469a1763e.png'
```

This user registered on 9/28, the same day the HM WP got migrated to new VM. It's possible that some of the profile image directories didn't get moved to the new VM completely.

**Comment by humadragonbane** [comment]
I have booted up the old hm wp server and did find the missing 2adda287-a750-44d2-abbd-026469a1763e.png
the directory has been tar'd and syncd with the new server. should no longer have error above.

**Comment by yuanzhou** [comment]
Note: I've resolved the issue for Yuling Ma, for some reason this member has multiple profile records found and caused the strange issue for `phpserialize` failed to deserialize the data. Asked Chirs Csonka to email the members separately to notify their membership approval.
